--SELECT COUNT(U.ID) USERS,COUNT(T.ID) TOWNS ,COUNT(A.ID) ADDRESSS  FROM USERS U, TOWNS T,ADDRESS A WHERE A.USERID=U.ID AND A.TOWNID=T.ID

--SELECT 
--	U.USERNAME_ , U.NAMESURNAME, CT.CITY,T.TOWN,D.DISTRICT,A.ADDRESSTEXT,O.ID ORDERID,O.DATE_,O.TOTALPRICE,P.DATE_ AS PAYMENTDATE,
--	P.APPROVECODE,I.DATE_ INVOICEDATE,I.CARGOFICHENO,ITM.ITEMCODE,ITM.ITEMNAME,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
--FROM		
--	ORDERS O
--INNER JOIN	USERS U ON U.ID=O.USERID
--INNER JOIN	ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN	PAYMENTS P ON P.ORDERID=O.ID
--INNER JOIN	INVOICES I ON I.ORDERID=O.ID

--INNER JOIN	ORDERDETAILS OD ON OD.ORDERID=O.ID
--INNER JOIN	ITEMS ITM ON ITM.ID=OD.ITEMID
--INNER JOIN	CITIES CT ON CT.ID=A.CITYID
--INNER JOIN	TOWNS T ON T.ID=A.TOWNID
--INNER JOIN	DISTRICTS D ON D.ID=A.DISTRICTID

--WHERE
--	U.NAMESURNAME='Talha CANIKARA'
--	O.ID=26121

--SELECT CT.CITY,SUM(O.TOTALPRICE) TOTALPRICE,SUM(OD.AMOUNT) AMOUNT,COUNT(DISTINCT O.ID) TOTALORDER

--FROM
--ORDERS O
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--GROUP BY CT.CITY
--ORDER BY SUM(O.TOTALPRICE) DESC

--SELECT IT.CATEGORY1,IT.CATEGORY2,IT.CATEGORY3,IT.CATEGORY4,SUM(O.TOTALPRICE) TOTALPRICE,COUNT(DISTINCT O.ID) TOTALORDER,
--SUM(O.TOTALPRICE)/COUNT(DISTINCT O.ID) MEANPRICE

--FROM 
--ORDERDETAILS OD
--INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
--INNER JOIN ORDERS O ON O.ID=OD.ORDERID
--GROUP BY IT.CATEGORY1,IT.CATEGORY2,IT.CATEGORY3,IT.CATEGORY4
--ORDER BY IT.CATEGORY1 

--SELECT IT.CATEGORY1,SUM(O.TOTALPRICE) TOTALPRICE,SUM(OD.AMOUNT) TOTALAMOUNT,COUNT(DISTINCT O.ID) TOTALORDER,
--SUM(O.TOTALPRICE)/SUM(OD.AMOUNT) MEANPRICE

--FROM 
--ORDERDETAILS OD
--INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
--INNER JOIN ORDERS O ON O.ID=OD.ORDERID
--GROUP BY IT.CATEGORY1
--ORDER BY IT.CATEGORY1 

--SELECT  CONVERT (DATE,O.DATE_) ORDERDATE,COUNT(DISTINCT O.ID) TOTALORDER

--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID= O.ID
--GROUP BY  CONVERT (DATE,O.DATE_)
--ORDER BY  CONVERT (DATE,O.DATE_) 

--SELECT  DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_) ORDERMONTH,COUNT(DISTINCT O.ID) TOTALORDER
--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID= O.ID
--GROUP BY   DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_)
--ORDER BY   DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_) 


--SELECT  DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_) ORDERMONTH,
--CASE 
--	WHEN DATEPART (MONTH,O.DATE_)=1 THEN 'JANUARY' 
--	WHEN DATEPART (MONTH,O.DATE_)=2 THEN 'FEBRUARY' 
--	WHEN DATEPART (MONTH,O.DATE_)=3 THEN 'MARCH' 
--	WHEN DATEPART (MONTH,O.DATE_)=4 THEN 'APRÝL'
--	WHEN DATEPART (MONTH,O.DATE_)=5 THEN 'MAY' 
--	WHEN DATEPART (MONTH,O.DATE_)=6 THEN 'JUNE' 
--	WHEN DATEPART (MONTH,O.DATE_)=7 THEN 'JULY' 
--	WHEN DATEPART (MONTH,O.DATE_)=8 THEN 'AUGUST'
--	WHEN DATEPART (MONTH,O.DATE_)=9 THEN 'SEMPTEMBER'
--	WHEN DATEPART (MONTH,O.DATE_)=10 THEN 'OCTOBER'
--	WHEN DATEPART (MONTH,O.DATE_)=11THEN 'NOVEMBER'
--	WHEN DATEPART (MONTH,O.DATE_)=12THEN 'DECEMBER' 
--END MONTH_NAME,COUNT(DISTINCT O.ID) TOTALORDER
--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID= O.ID
--GROUP BY   DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_)
--ORDER BY   DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_)


--SELECT  OD.ORDERID OD_ORDERID,O.ID ORDER_ID--,COUNT(DISTINCT O.ID) TOTALORDER

--FROM ORDERS O
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID= O.ID
--GROUP BY OD.ORDERID,O.ID--,COUNT(DISTINCT O.ID)
--ORDER BY  CONVERT (DATE,O.DATE_) 

--SELECT DATEPART (YEAR,P.DATE_),DATEPART(MONTH,P.DATE_),
--CASE
--	WHEN P.PAYMENTTYPE=1 THEN 'CREDIT CARD'
--	WHEN P.PAYMENTTYPE=2 THEN 'BANK TRANSFER'
--END AS PAYMENTTYPE,
--SUM(O.TOTALPRICE) TOTALPRICE,SUM(OD.AMOUNT) TOTALAMOUNT

--FROM PAYMENTS P	
--INNER JOIN ORDERS O ON O.ID=P.ORDERID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--GROUP BY P.PAYMENTTYPE,DATEPART (YEAR,P.DATE_),DATEPART(MONTH,P.DATE_)--,O.TOTALPRICE--,SUM(OD.AMOUNT)

--SELECT  DATEPART(MONTH,O.DATE_),(DATEDIFF (HOUR,O.DATE_,I.DATE_))/COUNT(O.ID)

--FROM ORDERS O
--INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--WHERE DATEPART(MONTH,O.DATE_)=1
--GROUP BY  DATEPART(MONTH,O.DATE_),(DATEDIFF (HOUR,O.DATE_,I.DATE_))/COUNT(O.ID)

SELECT DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_),COUNT(DISTINCT O.ID) TOTALORDER,SUM(DATEDIFF (HOUR,O.DATE_,I.DATE_)) TOTALHOUR,SUM(DATEDIFF (HOUR,O.DATE_,I.DATE_))/COUNT(O.ID)
FROM ORDERS O
INNER JOIN INVOICES I ON I.ORDERID=O.ID
--WHERE DATEPART(MONTH,O.DATE_) AND DATEPART(YEAR,O.DATE_)
GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)--,(DATEDIFF (HOUR,O.DATE_,I.DATE_))
ORDER BY DATEPART(MONTH,O.DATE_)



























