---------------------| MERGE TWO TABLE |-------------------
--- SELECT A.COL1, A.COL2, B.COL3, B.COL4  FROM TABLE1 A, TABLE2 B  WHERE A.PK_COL=B.FK_COL



--SELECT USERS.*, ADDRESS.ADDRESSTEXT FROM USERS,ADDRESS
--WHERE USERS.ID=ADDRESS.USERID AND USERS.ID=4

---------------------| USING ALIAS |---------------------------------------------------
--SELECT U.NAMESURNAME AS ADSOYAD,U.EMAIL ePOSTA,U.GENDER,U.BIRTHDATE, A.ADDRESSTEXT FROM USERS U,ADDRESS A
--WHERE U.ID=A.USERID AND U.ID=4

---------------------| USING MORE THAN TWO TABLES |------------------------------
--SELECT U.NAMESURNAME AS ADSOYAD,U.EMAIL ePOSTA,U.GENDER,U.BIRTHDATE,C.COUNTRY ULKE,CT.CITY AS SEHIR, A.ADDRESSTEXT ACIKADRES 
--FROM USERS U,ADDRESS A, COUNTRIES C,CITIES CT
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID AND CT.CITY= 'ÝSTANBUL'
--ORDER BY U.NAMESURNAME

--SELECT COUNT(DISTINCT U.NAMESURNAME)
--FROM USERS U,ADDRESS A, COUNTRIES C,CITIES CT
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID

--SELECT U.NAMESURNAME,COUNT(DISTINCT A.ADDRESSTEXT) TOTALADDRESS, COUNT(DISTINCT C.COUNTRY) TOTALCOUNTRY,COUNT(DISTINCT CT.CITY)
--FROM USERS U,ADDRESS A, COUNTRIES C,CITIES CT
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--GROUP BY U.NAMESURNAME

--SELECT U.NAMESURNAME,COUNT(DISTINCT A.ADDRESSTEXT) TOTALADDRESS, COUNT(DISTINCT C.COUNTRY) TOTALCOUNTRY,COUNT(DISTINCT CT.CITY)
--FROM USERS U,ADDRESS A, COUNTRIES C,CITIES CT
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--GROUP BY U.NAMESURNAME 
--HAVING COUNT(DISTINCT A.ADDRESSTEXT)>=2

--SELECT CT.CITY,COUNT(DISTINCT D.DISTRICT) DISTRICT,COUNT(DISTINCT U.NAMESURNAME) USERS 
--FROM USERS U,ADDRESS A, COUNTRIES C,CITIES CT, TOWNS T,DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
--GROUP BY CT.CITY, T.TOWN


------------------------------| JOIN |------------------------------------------------

-- SELECT A.COL1, A.COL2, B.COL3, B.COL4  FROM TABLE1 A JOIN TABLE2 B ON A.PK_COL=B.FK_COL


SELECT U.NAMESURNAME,U.EMAIL,C.COUNTRY,CT.CITY,D.DISTRICT,A.ADDRESSTEXT
FROM  USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID 
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID












