USE ETRADE4
--SET STATISTICS IO ON     -- TO SEE HOW MANY PAGE IT READ

--SELECT ITM.ITEMCODE,ITM.ITEMNAME,
--(SELECT MIN (UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
--(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVERAGEPRICE,
--(SELECT SUM (AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
--(SELECT SUM (LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALPRICE

--FROM ITEMS ITM
--ORDER BY ITM.ITEMNAME

----SET STATISTICS IO ON -- TO SEE HOW MANY PAGE IT READ

--SELECT ITM.ITEMCODE,ITM.ITEMNAME,
--(SELECT MIN (UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
--(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVERAGEPRICE,
--(SELECT SUM (AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
--(SELECT SUM (LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALPRICE,

--FROM ITEMS ITM
--ORDER BY ITM.ITEMNAME

--SELECT ITM.ITEMCODE,ITM.ITEMNAME,
--(SELECT MIN (UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
--(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVERAGEPRICE,
--(SELECT SUM (AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
--(SELECT SUM (LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALPRICE,
--(
--SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS MONTH_ FROM ORDERDETAILS OD
--INNER JOIN ORDERS O ON OD.ORDERID=O.ID
--WHERE OD.ITEMID=ITM.ID
--GROUP BY DATEPART(MONTH,O.DATE_)
--ORDER BY SUM(AMOUNT) DESC
--) AS THEMONTHMAXSALE

--FROM ITEMS ITM
--ORDER BY ITM.ITEMNAME


--SELECT ITM.ITEMCODE,ITM.ITEMNAME,
--(SELECT MIN (UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
--(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVERAGEPRICE,
--(SELECT SUM (AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
--(SELECT SUM (LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALPRICE,
--(
--SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS MONTH_ FROM ORDERDETAILS OD
--INNER JOIN ORDERS O ON OD.ORDERID=O.ID
--WHERE OD.ITEMID=ITM.ID
--GROUP BY DATEPART(MONTH,O.DATE_)
--ORDER BY SUM(AMOUNT) DESC
--) AS THEMONTHMAXSALE

--FROM ITEMS ITM
--WHERE (SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) IS NULL
--ORDER BY ITM.ITEMNAME


--SELECT ITM.ITEMCODE,ITM.ITEMNAME,
--(SELECT MIN (UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
--(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVERAGEPRICE,
--(SELECT SUM (AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
--(SELECT SUM (LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALPRICE,
--(
--SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS MONTH_ FROM ORDERDETAILS OD
--INNER JOIN ORDERS O ON OD.ORDERID=O.ID
--WHERE OD.ITEMID=ITM.ID
--GROUP BY DATEPART(MONTH,O.DATE_)
--ORDER BY SUM(AMOUNT) DESC
--) AS THEMONTHMAXSALE

--FROM ITEMS ITM
--WHERE ITM.ID NOT IN
--(SELECT ITEMID FROM ORDERDETAILS)
--ORDER BY ITM.ITEMNAME


--SELECT U.* ,A.ADDRESSTEXT FROM USERS U
--INNER JOIN ADDRESS A ON U.ID=A.USERID
--WHERE U.ID=1
--ORDER BY A.ID DESC


SELECT U.* ,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS  WHERE USERID=U.ID ORDER BY ID DESC) LASTADDRESS,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS  WHERE USERID=U.ID ORDER BY ID ) FIRSTADDRESS,
(SELECT COUNT( ADDRESSTEXT) FROM ADDRESS  WHERE USERID=U.ID  ) TOTALADDRESS


FROM USERS U



